// <auto-generated />
namespace KronoBattleship.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview1-19506-01")]
    public sealed partial class playerState2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(playerState2));
        
        string IMigrationMetadata.Id
        {
            get { return "201912011622524_playerState2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
